services:
  web:
    image: nginx
    ports:
      - 433:443
    volumes:
      - .:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl/nginx.crt:/etc/nginx/ssl/nginx.crt
      - ./ssl/nginx.key:/etc/nginx/ssl/nginx.key

  api:
    build: .
    env_file: ".env"
    environment:
      Usuario_Mongo: ${Usuario_Mongo}
      Usuario_Password: ${Usuario_Password}
      MongoHost: ${MongoHost}
    depends_on:
      - db

  db:
    image: mongo
    env_file: ".env"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${Usuario_Mongo}
      MONGO_INITDB_ROOT_PASSWORD: ${Usuario_Password}
      MONGO_INITDB_DATABASE: mydatabase
    volumes:
      - ./db:/data/db