services:
  web:
    image: nginx
    ports:
      - 80:443
    volumes:
      - .:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl/nginx.crt:/etc/nginx/ssl/nginx.crt
      - ./ssl/nginx.key:/etc/nginx/ssl/nginx.key

  depends:
    build: .
    ports:
      - 3000:3000
    env_file: ".env"
    environment:
      MONGO_USER: ${Usuario_Mongo}
      MONGO_PASSWORD: ${Usuario_Password}
      MONGOHOST: ${MongoHost}
    depends_on:
      - db

  db:
    image: mongo
    ports:
      - 27017:27017
    env_file: ".env"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${Usuario_Mongo}
      MONGO_INITDB_ROOT_PASSWORD: ${Usuario_Password}
      MONGO_INITDB_DATABASE: mydatabase
    volumes:
      - ./db:/data/db