services:
  web:
    image: nginx
    ports:
      - 80:443
    volumes:
      - .:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl/nginx.crt:/etc/nginx/ssl/nginx.crt
      - ./ssl/nginx.key:/etc/nginx/ssl/nginx.key

  depends:
    build: .
    ports:
      - 3000:3000
    env_file: ".env"
    environment:
      MONGO_USER: carloschaconcazallas0_db_user
      MONGO_PASSWORD: carloszz156
      MONGOHOST: mibasedatos.mtlbf9y.mongodb.net
    depends_on:
      - db

  db:
    image: mongo
    ports:
      - 27017:27017
    env_file: ".env"
    environment:
      MONGO_INITDB_ROOT_USERNAME: carloschaconcazallas0_db_user
      MONGO_INITDB_ROOT_PASSWORD: carloszz156
      MONGO_INITDB_DATABASE: mydatabase
    volumes:
      - ./db:/data/db