services:
  #web:
  #  image: nginx
  #  ports:
  #    - 80:80
  #  volumes:
  #    - .:/usr/share/nginx/html

  web:
    build: .
    ports:
      - 3000:3000
    env_file: ".env"
    environment:
      MONGO_USER: ${Usuario_Mongo}
      MONGO_PASSWORD: ${Usuario_Password}
      MONGOHOST: db
    depends_on:
      - db

  db:
    image: mongo
    ports:
      - 27017:27017
    env_file: ".env"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${Usuario_Mongo}
      MONGO_INITDB_ROOT_PASSWORD: ${Usuario_Password}
      MONGO_INITDB_DATABASE: mydatabase
    volumes:
      - ./db:/data/db